name: route_definer
description: An advanced router for Flutter with support for parsing routes, parameters, and guards.
version: 1.0.2
homepage: https://github.com/arlamend7/flutter_route_definer
repository: https://github.com/arlamend7/flutter_route_definer
issue_tracker: https://github.com/arlamend7/flutter_route_definer/issues
license: MIT
example: example/main.dart

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0